INSERT INTO ARTICLE(title, content) VALUES('오늘의 상식', '상식을 여기에 쭈루룩');
INSERT INTO ARTICLE(title, content) VALUES('저녁 메뉴 추천', '한식 중식 일식..');
INSERT INTO ARTICLE(title, content) VALUES('주간 일기 예보', '월화수목금토일 맑음');
INSERT INTO MEMBER(email, password) VALUES('bomig88@gmail.com', 'test');
INSERT INTO ARTICLE(title, content) VALUES('당신의 인생 영화는?', '댓글 고');
INSERT INTO ARTICLE(title, content) VALUES('당신의 소울 푸드는?', '댓글 고고');
INSERT INTO ARTICLE(title, content) VALUES('당신의 취미는?', '댓글 고고고');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Park', '굿 윌 헌팅');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Kim', '아이 엠 샘');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Choi', '쇼생크 탈출');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'Park', '치킨');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'Kim', '샤브샤브');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'Choi', '초밥');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Park', '조깅');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Kim', '유튜브');
INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Choi', '독서');